version: "3"
services:
  service:
    build: ./image-service/
    container_name: image-service
    ports:
      - "8080:8080"
    depends_on:
      - "database"
      - "message-broker"
    links:
      - "database"
      - "message-broker"
    restart: always
  database:
    image: postgres:15.1-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=images
  message-broker:
    image: rabbitmq:3.11.4-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin